namespace MyRoutine.Service
{
    public enum PickyMessageType
    {
        Introduction,
        IntroductionMobile,
        Greeting,
        GreetingBeenAWhile,
        CasualTalk,
        FormErrors,
        ChangeUserDetailsSuccess,
        ChangePasswordSuccess,
        CreateTaskSuccess,
        EditTaskSuccess,
        ArchiveTaskSuccess,
        RestoreTaskSuccess,
        DeleteTaskConfirm,
        DeleteTaskSuccess,
        CreatePickyMessageSuccess,
        EditPickyMessageSuccess,
        DeletePickyMessageConfirm,
        DeletePickyMessageSuccess,
        BanUserConfirm,
        BanUserSuccess,
        UnbanUserConfirm,
        UnbanUserSuccess,
        DeleteUserConfirm,
        DeleteUserSuccess,
        ScheduleSaveSuccess
    }
}